version = 1
disable_existing_loggers = false

[formatters.standard]
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[handlers.console]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "standard"
stream = "ext://sys.stdout"

[handlers.file]
class = "logging.handlers.RotatingFileHandler"
level = "DEBUG"
formatter = "standard"
filename = "logs.log"
maxBytes = 1048576
backupCount = 3

[root]
handlers = ["console", "file"]
level = "DEBUG"

# [loggers.parser]
# level = "DEBUG"

# [loggers.lexer]
# level = "INFO"